# Generated by Django 4.2.2 on 2023-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_score',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
