# Generated by Django 4.2.2 on 2023-06-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_participant_image_url_participant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/participant_images/'),
        ),
    ]
