# Generated by Django 4.2.2 on 2023-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_participant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_final_round',
            field=models.BooleanField(default=False),
        ),
    ]
