# Generated by Django 4.2.2 on 2023-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_round_is_final_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='is_final_round',
        ),
        migrations.AddField(
            model_name='round',
            name='num_winners',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
