# Generated by Django 4.2.2 on 2023-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_round_is_final_round_round_num_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='num_winners',
            field=models.IntegerField(verbose_name='Number of winners'),
        ),
    ]
