# Generated by Django 4.2.2 on 2023-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_round_num_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
