# Generated by Django 4.2.2 on 2023-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_round_location_alter_round_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='start_date',
            field=models.DateField(),
        ),
    ]
